### ISSUE TITLE
[QUESTION]: Get the actual size of primary and secondary panel

### ISSUE THREAD

**Issue by nmpatzios** [martinnov92/React-Splitters#11]
Hi,
I  am trying to return the actual height when  the panel resizing  horizontally to apply a blur css when its 4%.
Can you provide an example how to actual get the size using the **onDragFinished**

Thanks in advance
Nikos

**Comment by martinnov92** [comment]
Hello, you can use `ref` for this.

Simply add `ref={(node) => this.splitter = node}` to your Splitter component and then in `onDragFinished` callback you can use it like this:

```js
    this.split.paneWrapper; // actual div where you can get its width, height
    this.split.panePrimary.div; // get access to div element
    this.split.paneNotPrimary.div; // get access to div element, you can use clientWidht, clientHeight on all of them to get the actual size
```

Hope this helps.
Martin
