### ISSUE TITLE
 [QUESTION]: handle-bar css

### ISSUE THREAD

**Issue by Shawnfoto** [martinnov92/React-Splitters#13]
Excuse me, How can i setting the postPoned handle-bar moving shadow in css?
like this, point in the red rectangle, thanks
![image 25](https://user-images.githubusercontent.com/18244561/38083779-32ac1bca-337d-11e8-8dfc-0008c8b09e6a.png)

**Comment by martinnov92** [comment]
Hello, if you need to style it, its class name is `handle-bar_clone`. Hope it helps

**Comment by Shawnfoto** [comment]
Yes,but seem didn't work. Become instant move splitter
https://www.flickr.com/photos/rpd11140/41050127532/

**Comment by Shawnfoto** [comment]
oh, i solve the problem, the className no same with my ".layout-splitter_clone"
