### ISSUE TITLE
typescript react types conflict

### ISSUE THREAD

**Issue by paulspiteri** [martinnov92/React-Splitters#16]
hi
I've seen some problems when using different version of @types/react in my project, as your project has a conflicting dependency. 
Perhaps all the @types should just be devDependencies?

**Comment by Sergiioo** [comment]
+1 - this is impacting me too. `@types` in general should be `devDependencies` imho.

**Comment by martinnov92** [comment]
Hello, this will be fixed in next release. thank you

**Comment by martinnov92** [comment]
I just released new version, I hope this issue is fixed for you
