### ISSUE TITLE
Adding custom properties

### ISSUE THREAD

**Issue by harmeetjaipur** [martinnov92/React-Splitters#5]
Hi, I want to first commend how simple and yet efficient this package is. I was wondering if there was a way to add custom properties to the `Splitter` component by any chance?

**Comment by martinnov92** [comment]
Hello, I am glad this package helps you and thank you for your nice words :) It is not possible to do it now, but what custom properties would you like to add to `Splitter ` component? Thank you

**Comment by harmeetjaipur** [comment]
Boolean values for instance. So that I can add methods on the Splitter.

**Comment by martinnov92** [comment]
Unfortunately that is not possible for now. But feel free to fork it and update it as you need :)
