### ISSUE TITLE
Unable to work with React 16.0.0

### ISSUE THREAD

**Issue by reyicare** [martinnov92/React-Splitters#6]
React-Splitter don't work with React 16.0.0. This throw a new => Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null at Splitter.getSize.

**Comment by martinnov92** [comment]
Hello, that is odd. I tried it in React 16 without any issue. I will try to investigate this issue later today. Thank you :)

**Comment by reyicare** [comment]
Hello, thanks for your quick answer. Ok, strange, because impossible for me to run with react 16.0.0 and when I downgrade to 15.6.1 that's good. Thanks

**Comment by martinnov92** [comment]
Hello again, I tried splitters with React 16 and it seems ok. Could you please provide some example branch where I could try it? Thank you

**Comment by mikerussellnz** [comment]
Getting same error on this line:
  var primaryPane = ReactDOM.findDOMNode(this.panePrimary).getBoundingClientRect();
    
  Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at Splitter.getSize (Splitter.js:45)
    at Splitter.handleMouseDown (Splitter.js:117)
    at onMouseDown (HandleBar.js:22)

**Comment by martinnov92** [comment]
I will have a look at this later today, thank you

**Comment by martinnov92** [comment]
Please install new version of this package

**Comment by don-p** [comment]
I still see this issue, with latest package v1.2.0, using React 16.7.

See issue: https://github.com/martinnov92/React-Splitters/issues/20

**Comment by abhi2526** [comment]
I'm also facing the same issue that can't read property **'getBoundingClientRect' of null**. Whenever I click on the section separator/resize the panels.

I'm using following versions:
**"m-react-splitters": "^1.2.0",
"react": "^16.6.3"**

**_Please provide me the solution or case handling as soon as possible._**

![m-react-splitter_error](https://user-images.githubusercontent.com/33726616/58185254-56094280-7cd0-11e9-809a-4dd861a6ae77.png)

Thank You

**Comment by abhi2526** [comment]
Hi @martinnov92 here is my sample snippet also which properties i'm using.

![image](https://user-images.githubusercontent.com/33726616/58228263-cc975600-7d4b-11e9-9a5d-95bfb96b2c78.png)

Whenever I even clicked on the separator it generates an error, also when resize the panel.
One more thing, especially when I'm on other page and then visit on this particular page, it generates the above mentioned error of **'getBoundingClientRect'** of null.
